(deftheme sanityinc-tomorrow-eighties-mine
  "Created 2021-12-29.")

(custom-theme-set-variables
 'sanityinc-tomorrow-eighties-mine
 '(frame-background-mode 'dark)
 '(beacon-color "#f2777a")
 '(ansi-color-names-vector ["#2d2d2d" "#f2777a" "#99cc99" "#ffcc66" "#6699cc" "#cc99cc" "#66cccc" "#cccccc"])
 '(ansi-color-faces-vector [default bold shadow italic underline bold bold-italic bold])
 '(window-divider-mode nil))

(custom-theme-set-faces
 'sanityinc-tomorrow-eighties-mine
 '(bold ((((class color) (min-colors 89)) (:weight bold))))
 '(bold-italic ((((class color) (min-colors 89)) (:slant italic :weight bold))))
 '(underline ((((class color) (min-colors 89)) (:underline t))))
 '(italic ((((class color) (min-colors 89)) (:slant italic))))
 '(font-lock-builtin-face ((((class color) (min-colors 89)) (:foreground "#cc99cc"))))
 ;; '(font-lock-comment-delimiter-face ((((class color) (min-colors 89)) (:foreground "#999999" :slant italic))))
 ;; '(font-lock-comment-face ((((class color) (min-colors 89)) (:foreground "#999999" :slant italic))))
 '(font-lock-comment-delimiter-face ((((class color) (min-colors 89)) (:foreground "#999999"))))
 '(font-lock-comment-face ((((class color) (min-colors 89)) (:foreground "#999999"))))
 '(font-lock-constant-face ((((class color) (min-colors 89)) (:foreground "#6699cc"))))
 '(font-lock-doc-face ((((class color) (min-colors 89)) (:foreground "#cc99cc"))))
 '(font-lock-function-name-face ((((class color) (min-colors 89)) (:foreground "#f99157"))))
 '(font-lock-keyword-face ((((class color) (min-colors 89)) (:foreground "#99cc99"))))
 '(font-lock-negation-char-face ((((class color) (min-colors 89)) (:foreground "#6699cc"))))
 '(font-lock-preprocessor-face ((((class color) (min-colors 89)) (:foreground "#cc99cc"))))
 '(font-lock-regexp-grouping-backslash ((((class color) (min-colors 89)) (:foreground "#ffcc66"))))
 '(font-lock-regexp-grouping-construct ((((class color) (min-colors 89)) (:foreground "#cc99cc"))))
 ;; '(font-lock-string-face ((t (:foreground "#9acd32"))))
 '(font-lock-string-face ((t (:foreground "#3cb371"))))
 '(font-lock-type-face ((((class color) (min-colors 89)) (:foreground "#6699cc"))))
 '(font-lock-variable-name-face ((((class color) (min-colors 89)) (:foreground "#ffcc66"))))
 '(font-lock-warning-face ((((class color) (min-colors 89)) (:weight bold :foreground "#f2777a"))))
 '(shadow ((((class color) (min-colors 89)) (:foreground "#999999"))))
 '(fill-column-indicator ((((class color) (min-colors 89)) (:foreground "#515151"))))
 '(success ((((class color) (min-colors 89)) (:foreground "#99cc99"))))
 '(error ((((class color) (min-colors 89)) (:foreground "#f2777a"))))
 '(warning ((((class color) (min-colors 89)) (:foreground "#f99157"))))
 '(tooltip ((((class color) (min-colors 89)) (:foreground "#ffcc66" :background "#2d2d2d" :inverse-video t))))
 '(cursor ((((class color) (min-colors 89)) (:background "#f2777a"))))
 '(fringe ((((class color) (min-colors 89)) (:background "#333333333333" :foreground "#999999"))))
 '(line-number ((((class color) (min-colors 89)) (:background "#333333333333" :foreground "#999999"))))
 '(line-number-current-line ((((class color) (min-colors 89)) (:inherit line-number :foreground "#cccccc" :weight bold))))
 '(fill-column-indicator ((((class color) (min-colors 89)) (:foreground "#515151" :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :stipple nil))))
 '(vertical-border ((((class color) (min-colors 89)) (:foreground "#515151"))))
 '(border ((((class color) (min-colors 89)) (:background "#515151" :foreground "#393939"))))
 '(highlight ((((class color) (min-colors 89)) (:inverse-video nil :background "#393939"))))
 '(mode-line ((((class color) (min-colors 89)) (:foreground "#cccccc" :background "#515151" :weight normal :box (:line-width 1 :color "#515151")))))
 '(mode-line-buffer-id ((((class color) (min-colors 89)) (:foreground "#cc99cc" :background nil))))
 '(mode-line-inactive ((((class color) (min-colors 89)) (:inherit mode-line :foreground "#999999" :background "#393939" :weight normal))))
 '(mode-line-emphasis ((((class color) (min-colors 89)) (:foreground "#cccccc" :slant italic))))
 '(mode-line-highlight ((((class color) (min-colors 89)) (:foreground "#cc99cc" :box nil :weight bold))))
 '(minibuffer-prompt ((((class color) (min-colors 89)) (:foreground "#6699cc"))))
 '(region ((((class color) (min-colors 89)) (:background "#515151" :inverse-video nil :extend t))))
 '(secondary-selection ((((class color) (min-colors 89)) (:background "#393939" :extend t))))
 '(header-line ((((class color) (min-colors 89)) (:inherit mode-line-inactive :foreground "#66cccc" :background nil))))
 '(match ((((class color) (min-colors 89)) (:foreground "#6699cc" :background "#2d2d2d" :inverse-video t))))
 '(isearch ((((class color) (min-colors 89)) (:foreground "#ffcc66" :background "#2d2d2d" :inverse-video t))))
 '(lazy-highlight ((((class color) (min-colors 89)) (:foreground "#66cccc" :background "#2d2d2d" :inverse-video t))))
 '(isearch-fail ((((class color) (min-colors 89)) (:background "#2d2d2d" :inherit font-lock-warning-face :inverse-video t))))
 '(link ((((class color) (min-colors 89)) (:foreground nil :underline t))))
 '(widget-button ((((class color) (min-colors 89)) (:underline t))))
 '(widget-field ((((class color) (min-colors 89)) (:background "#515151" :box (:line-width 1 :color "#cccccc")))))
 '(term ((((class color) (min-colors 89)) (:foreground nil :background nil :inherit default))))
 '(term-color-black ((((class color) (min-colors 89)) (:foreground "#2d2d2d" :background "#2d2d2d"))))
 '(term-color-red ((((class color) (min-colors 89)) (:foreground "#f2777a" :background "#f2777a"))))
 '(term-color-green ((((class color) (min-colors 89)) (:foreground "#99cc99" :background "#99cc99"))))
 '(term-color-yellow ((((class color) (min-colors 89)) (:foreground "#ffcc66" :background "#ffcc66"))))
 '(term-color-blue ((((class color) (min-colors 89)) (:foreground "#6699cc" :background "#6699cc"))))
 '(term-color-magenta ((((class color) (min-colors 89)) (:foreground "#cc99cc" :background "#cc99cc"))))
 '(term-color-cyan ((((class color) (min-colors 89)) (:foreground "#66cccc" :background "#66cccc"))))
 '(term-color-white ((((class color) (min-colors 89)) (:foreground "#cccccc" :background "#cccccc"))))
 '(diary ((((class color) (min-colors 89)) (:foreground "#ffcc66"))))
 '(holiday ((((class color) (min-colors 89)) (:foreground "#2d2d2d" :background "#f99157"))))
 '(compilation-column-number ((((class color) (min-colors 89)) (:foreground "#ffcc66"))))
 '(compilation-line-number ((((class color) (min-colors 89)) (:foreground "#ffcc66"))))
 '(compilation-mode-line-exit ((((class color) (min-colors 89)) (:foreground "#99cc99"))))
 '(compilation-mode-line-fail ((((class color) (min-colors 89)) (:foreground "#f2777a"))))
 '(compilation-mode-line-run ((((class color) (min-colors 89)) (:foreground "#6699cc"))))
 '(completions-annotations ((((class color) (min-colors 89)) (:foreground "#999999" :slant italic))))
 '(completions-common-part ((((class color) (min-colors 89)) (:foreground "#6699cc"))))
 '(completions-first-difference ((((class color) (min-colors 89)) (:foreground "#f99157" :weight bold))))
 '(custom-variable-tag ((((class color) (min-colors 89)) (:foreground "#6699cc"))))
 '(custom-group-tag ((((class color) (min-colors 89)) (:foreground "#6699cc"))))
 '(custom-state ((((class color) (min-colors 89)) (:foreground "#99cc99"))))
 '(diff-added ((((class color) (min-colors 89)) (:foreground "#99cc99" :extend t))))
 '(diff-changed ((((class color) (min-colors 89)) (:foreground "#6699cc"))))
 '(diff-removed ((((class color) (min-colors 89)) (:foreground "#f99157" :extend t))))
 '(diff-header ((((class color) (min-colors 89)) (:foreground "#66cccc" :background nil :extend t))))
 '(diff-file-header ((((class color) (min-colors 89)) (:foreground "#6699cc" :background nil :extend t))))
 '(diff-hunk-header ((((class color) (min-colors 89)) (:foreground "#cc99cc"))))
 '(diff-indicator-added ((((class color) (min-colors 89)) (:inherit diff-added))))
 '(diff-indicator-changed ((((class color) (min-colors 89)) (:inherit diff-changed))))
 '(diff-indicator-removed ((((class color) (min-colors 89)) (:inherit diff-removed))))
 '(diff-refine-added ((((class color) (min-colors 89)) (:foreground "#66cccc"))))
 '(diff-refine-changed ((((class color) (min-colors 89)) (:foreground "#ffcc66"))))
 '(diff-refine-removed ((((class color) (min-colors 89)) (:foreground "#f2777a"))))
 '(eldoc-highlight-function-argument ((((class color) (min-colors 89)) (:foreground "#99cc99" :weight bold))))
 '(flyspell-incorrect ((((class color) (min-colors 89)) (:underline (:style wave :color "#f2777a")))))
 '(hi-black-hb ((((class color) (min-colors 89)) (:weight bold))))
 '(hi-blue ((((class color) (min-colors 89)) (:foreground "#2d2d2d" :background "#6699cc"))))
 '(hi-blue-b ((((class color) (min-colors 89)) (:foreground "#6699cc" :weight bold))))
 '(hi-green ((((class color) (min-colors 89)) (:foreground "#2d2d2d" :background "#99cc99"))))
 '(hi-green-b ((((class color) (min-colors 89)) (:foreground "#99cc99" :weight bold))))
 '(hi-pink ((((class color) (min-colors 89)) (:foreground "#2d2d2d" :background "#66cccc"))))
 '(hi-red-b ((((class color) (min-colors 89)) (:foreground "#f2777a" :weight bold))))
 '(hi-yellow ((((class color) (min-colors 89)) (:foreground "#2d2d2d" :background "#ffcc66"))))
 '(ido-subdir ((((class color) (min-colors 89)) (:foreground "#cc99cc"))))
 '(ido-first-match ((((class color) (min-colors 89)) (:foreground "#f99157"))))
 '(ido-only-match ((((class color) (min-colors 89)) (:foreground "#99cc99"))))
 '(ido-indicator ((((class color) (min-colors 89)) (:foreground "#f2777a" :background "#2d2d2d"))))
 '(ido-virtual ((((class color) (min-colors 89)) (:foreground "#999999"))))
 '(Info-quoted ((((class color) (min-colors 89)) (:inherit font-lock-constant-face))))
 '(info-index-match ((((class color) (min-colors 89)) (:inherit isearch))))
 '(info-menu-header ((((class color) (min-colors 89)) (:foreground "#99cc99" :weight bold :height 1.4))))
 '(info-menu-star ((((class color) (min-colors 89)) (:foreground "#ffcc66"))))
 '(info-node ((((class color) (min-colors 89)) (:foreground "#99cc99" :weight bold :slant italic))))
 '(info-title-1 ((((class color) (min-colors 89)) (:weight bold :height 1.4))))
 '(info-title-2 ((((class color) (min-colors 89)) (:weight bold :height 1.2))))
 '(info-title-3 ((((class color) (min-colors 89)) (:weight bold :foreground "#f99157"))))
 '(info-title-4 ((((class color) (min-colors 89)) (:weight bold :foreground "#cc99cc"))))
 '(info-xref-visited ((((class color) (min-colors 89)) (:foreground "#999999" :underline t))))
 '(org-agenda-structure ((((class color) (min-colors 89)) (:foreground "#cc99cc"))))
 '(org-agenda-current-time ((((class color) (min-colors 89)) (:foreground "#ffcc66"))))
 '(org-agenda-date ((((class color) (min-colors 89)) (:foreground "#6699cc" :underline nil))))
 '(org-agenda-done ((((class color) (min-colors 89)) (:foreground "#99cc99"))))
 '(org-agenda-dimmed-todo-face ((((class color) (min-colors 89)) (:foreground "#999999"))))
 '(org-block ((((class color) (min-colors 89)) (:background "#333333333333"))))
 '(org-block-begin-line ((((class color) (min-colors 89)) (:background "#2d2d2d" :foreground "#999999" :slant italic))))
 '(org-block-end-line ((((class color) (min-colors 89)) (:background "#2d2d2d" :foreground "#999999" :slant italic))))
 '(org-code ((((class color) (min-colors 89)) (:foreground "#ffcc66"))))
 '(org-column ((((class color) (min-colors 89)) (:background "#515151"))))
 '(org-column-title ((((class color) (min-colors 89)) (:inherit org-column :weight bold :underline t))))
 '(org-date ((((class color) (min-colors 89)) (:foreground "#6699cc" :underline t))))
 '(org-date-selected ((((class color) (min-colors 89)) (:foreground "#66cccc" :inverse-video t))))
 '(org-document-info ((((class color) (min-colors 89)) (:foreground "#66cccc"))))
 '(org-document-info-keyword ((((class color) (min-colors 89)) (:foreground "#99cc99"))))
 '(org-document-title ((((class color) (min-colors 89)) (:weight bold :foreground "#f99157" :height 1.4))))
 '(org-done ((((class color) (min-colors 89)) (:foreground "#99cc99"))))
 '(org-ellipsis ((((class color) (min-colors 89)) (:foreground "#999999"))))
 '(org-footnote ((((class color) (min-colors 89)) (:foreground "#66cccc"))))
 '(org-formula ((((class color) (min-colors 89)) (:foreground "#f2777a"))))
 '(org-hide ((((class color) (min-colors 89)) (:foreground "#2d2d2d" :background "#2d2d2d"))))
 '(org-headline-done ((((class color) (min-colors 89)) (:foreground nil :strike-through t))))
 '(org-link ((((class color) (min-colors 89)) (:foreground "#6699cc" :underline t))))
 '(org-mode-line-clock-overrun ((((class color) (min-colors 89)) (:inherit mode-line :background "#f2777a"))))
 '(org-scheduled ((((class color) (min-colors 89)) (:foreground "#99cc99"))))
 '(org-scheduled-previously ((((class color) (min-colors 89)) (:foreground "#66cccc"))))
 '(org-scheduled-today ((((class color) (min-colors 89)) (:foreground "#99cc99"))))
 '(org-special-keyword ((((class color) (min-colors 89)) (:foreground "#f99157"))))
 '(org-table ((((class color) (min-colors 89)) (:foreground "#cc99cc"))))
 '(org-time-grid ((((class color) (min-colors 89)) (:foreground "#ffcc66"))))
 '(org-todo ((((class color) (min-colors 89)) (:foreground "#f2777a"))))
 '(org-upcoming-deadline ((((class color) (min-colors 89)) (:foreground "#f99157"))))
 '(org-warning ((((class color) (min-colors 89)) (:weight bold :foreground "#f2777a"))))
 '(outline-1 ((((class color) (min-colors 89)) (:inherit nil :foreground "#6699cc"))))
 '(outline-2 ((((class color) (min-colors 89)) (:inherit nil :foreground "#cc99cc"))))
 '(outline-3 ((((class color) (min-colors 89)) (:inherit nil :foreground "#66cccc"))))
 '(outline-4 ((((class color) (min-colors 89)) (:inherit nil :foreground "#ffcc66"))))
 '(outline-5 ((((class color) (min-colors 89)) (:inherit nil :foreground "#f99157"))))
 '(outline-6 ((((class color) (min-colors 89)) (:inherit nil :foreground "#6699cc"))))
 '(outline-7 ((((class color) (min-colors 89)) (:inherit nil :foreground "#cc99cc"))))
 '(outline-8 ((((class color) (min-colors 89)) (:inherit nil :foreground "#66cccc"))))
 '(show-paren-match ((((class color) (min-colors 89)) (:background "#cc99cc" :foreground "#2d2d2d"))))
 '(show-paren-mismatch ((((class color) (min-colors 89)) (:background "#f2777a" :foreground "#2d2d2d"))))
 '(speedbar-button-face ((((class color) (min-colors 89)) (:foreground "#99cc99"))))
 '(speedbar-directory-face ((((class color) (min-colors 89)) (:foreground "#f99157"))))
 '(speedbar-file-face ((((class color) (min-colors 89)) (:foreground "#66cccc"))))
 '(speedbar-highlight-face ((((class color) (min-colors 89)) (:inherit highlight))))
 '(speedbar-selected-face ((((class color) (min-colors 89)) (:foreground "#f2777a" :underline t))))
 '(speedbar-separator-face ((((class color) (min-colors 89)) (:foreground "#2d2d2d" :background "#6699cc" :overline "#2d2d2d"))))
 '(speedbar-tag-face ((((class color) (min-colors 89)) (:foreground "#ffcc66"))))
 '(tab-bar ((((class color) (min-colors 89)) (:height 1.2 :foreground "#999999" :background "#393939"))))
 '(tab-bar-tab ((((class color) (min-colors 89)) (:background "#515151" :foreground "#cc99cc" :inverse-video nil :box (:line-width 1 :style released-button)))))
 '(tab-bar-tab-inactive ((((class color) (min-colors 89)) (:inherit tab-bar-tab :background "#999999" :foreground "#393939" :inverse-video t))))
 '(tab-line ((((class color) (min-colors 89)) (:foreground "#999999" :background "#393939"))))
 '(trailing-whitespace ((((class color) (min-colors 89)) (:inherit whitespace-trailing))))
 '(window-divider ((((class color) (min-colors 89)) (:foreground "#999999"))))
 '(window-divider-first-pixel ((((class color) (min-colors 89)) (:foreground "#515151"))))
 '(window-divider-last-pixel ((((class color) (min-colors 89)) (:foreground "#515151"))))
 '(avy-background-face ((((class color) (min-colors 89)) (:foreground "#515151"))))
 '(avy-lead-face ((((class color) (min-colors 89)) (:foreground "#2d2d2d" :background "#ffcc66"))))
 '(avy-lead-face-0 ((((class color) (min-colors 89)) (:foreground "#2d2d2d" :background "#6699cc"))))
 '(avy-lead-face-1 ((((class color) (min-colors 89)) (:foreground "#2d2d2d" :background "#66cccc"))))
 '(avy-lead-face-2 ((((class color) (min-colors 89)) (:foreground "#2d2d2d" :background "#f99157"))))
 '(company-preview ((((class color) (min-colors 89)) (:foreground "#999999" :background "#515151"))))
 '(company-preview-common ((((class color) (min-colors 89)) (:inherit company-preview :foreground "#f2777a"))))
 '(company-preview-search ((((class color) (min-colors 89)) (:inherit company-preview :foreground "#6699cc"))))
 '(company-tooltip ((((class color) (min-colors 89)) (:background "#515151"))))
 '(company-tooltip-selection ((((class color) (min-colors 89)) (:foreground "#999999" :inverse-video t))))
 '(company-tooltip-common ((((class color) (min-colors 89)) (:inherit company-tooltip :foreground "#f2777a"))))
 '(company-tooltip-common-selection ((((class color) (min-colors 89)) (:inherit company-tooltip-selection :foreground "#f2777a"))))
 '(company-tooltip-search ((((class color) (min-colors 89)) (:inherit company-tooltip :foreground "#6699cc"))))
 '(company-tooltip-annotation ((((class color) (min-colors 89)) (:inherit company-tooltip :foreground "#99cc99"))))
 '(company-tooltip-annotation-selection ((((class color) (min-colors 89)) (:inherit company-tooltip-selection :foreground "#99cc99"))))
 '(company-scrollbar-bg ((((class color) (min-colors 89)) (:inherit 'company-tooltip :background "#393939"))))
 '(company-scrollbar-fg ((((class color) (min-colors 89)) (:background "#515151"))))
 '(company-echo-common ((((class color) (min-colors 89)) (:inherit company-echo :foreground "#f2777a"))))
 '(diff-hl-insert ((((class color) (min-colors 89)) (:foreground "#2d2d2d" :background "#99cc99"))))
 '(diff-hl-change ((((class color) (min-colors 89)) (:foreground "#2d2d2d" :background "#6699cc"))))
 '(diff-hl-delete ((((class color) (min-colors 89)) (:foreground "#2d2d2d" :background "#f2777a"))))
 '(highlight-symbol-face ((((class color) (min-colors 89)) (:inherit highlight))))
 '(hydra-face-blue ((((class color) (min-colors 89)) (:foreground "#6699cc"))))
 '(hydra-face-teal ((((class color) (min-colors 89)) (:foreground "#66cccc"))))
 '(hydra-face-pink ((((class color) (min-colors 89)) (:foreground "#cc99cc"))))
 '(hydra-face-red ((((class color) (min-colors 89)) (:foreground "#f2777a"))))
 '(hydra-face-amaranth ((((class color) (min-colors 89)) (:foreground "#f99157"))))
 '(ivy-action ((((class color) (min-colors 89)) (:foreground "#cc99cc"))))
 '(ivy-confirm-face ((((class color) (min-colors 89)) (:foreground "#99cc99"))))
 '(ivy-current-match ((((class color) (min-colors 89)) (:background "#515151"))))
 '(ivy-cursor ((((class color) (min-colors 89)) (:background "#515151"))))
 '(ivy-match-required-face ((((class color) (min-colors 89)) (:foreground "#f2777a" :background "#2d2d2d"))))
 '(ivy-remote ((((class color) (min-colors 89)) (:foreground "#f99157"))))
 '(ivy-subdir ((((class color) (min-colors 89)) (:foreground "#cc99cc"))))
 '(ivy-virtual ((((class color) (min-colors 89)) (:foreground "#999999"))))
 '(ivy-minibuffer-match-face-1 ((((class color) (min-colors 89)) (:foreground "#66cccc"))))
 '(ivy-minibuffer-match-face-2 ((((class color) (min-colors 89)) (:foreground "#ffcc66"))))
 '(ivy-minibuffer-match-face-3 ((((class color) (min-colors 89)) (:foreground "#6699cc"))))
 '(ivy-minibuffer-match-face-4 ((((class color) (min-colors 89)) (:foreground "#f99157"))))
 '(lispy-command-name-face ((((class color) (min-colors 89)) (:inherit font-lock-function-name-face :background "#393939"))))
 '(lispy-cursor-face ((((class color) (min-colors 89)) (:foreground "#2d2d2d" :background "#cccccc"))))
 '(lispy-face-hint ((((class color) (min-colors 89)) (:foreground "#99cc99" :background "#515151"))))
 '(persp-selected-face ((((class color) (min-colors 89)) (:foreground "#ffcc66" :weight bold))))
 '(swiper-line-face ((((class color) (min-colors 89)) (:underline t))))
 '(symbol-overlay-default-face ((((class color) (min-colors 89)) (:inherit highlight :underline t))))
 '(transient-enabled-suffix ((((class color) (min-colors 89)) (:foreground "#333333333333" :background "#99cc99" :weight bold))))
 '(transient-disabled-suffix ((((class color) (min-colors 89)) (:foreground "#cccccc" :background "#f2777a" :weight bold))))
 '(undo-tree-visualizer-default-face ((((class color) (min-colors 89)) (:foreground "#cccccc"))))
 '(undo-tree-visualizer-current-face ((((class color) (min-colors 89)) (:foreground "#99cc99" :weight bold))))
 '(undo-tree-visualizer-active-branch-face ((((class color) (min-colors 89)) (:foreground "#f2777a"))))
 '(undo-tree-visualizer-register-face ((((class color) (min-colors 89)) (:foreground "#ffcc66"))))
 '(default ((((class color) (min-colors 89)) (:foreground "#cccccc" :background "#2d2d2d")))))

(provide-theme 'sanityinc-tomorrow-eighties-mine)
